version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
  settings:
    depguard:
      rules:
        Main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    godot:
      scope: declarations
      capital: false
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
        - BUG
        - FIXME
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 120
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: true
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - goconst
          - gocyclo
          - gosec
          - mnd
        path: _test\.go
      - linters:
          - dupl
          - funlen
          - gocyclo
          - mnd
        path: ^internal/bench/
      - linters:
          - dupl
        path: ^internal/cli/commands/bench\.go$
      - linters:
          - gosec
        path: internal/
        text: weak cryptographic primitive
      - linters:
          - govet
        text: 'shadow: declaration of "err"'
      - linters:
          - godox
        path: internal/
        text: 'Line contains TODO/BUG/FIXME:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  whole-files: false
  new: false
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - gocritic
      severity: warning
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - mitl
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
