name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        go-version: ["1.24"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run go vet (blocking)
        run: go vet ./...

      - name: Run tests
        run: |
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Enforce per-file coverage >= 85% (digest core)
        run: |
          go run ./internal/tools/covercheck -profile coverage.out -threshold 85 -include mitl/internal/digest

      - name: Build binary
        run: |
          go build -o mitl cmd/mitl/main.go
          ./mitl version || true

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-mac

  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.3.1
          args: --timeout=5m --out-format=colored-line-number

  preflight-light:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build mitl
        run: |
          make build
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: Run preflight (light)
        run: bash scripts/preflight.sh --light --skip-docker
